[server]
serverEnv = "inline"
port = 8080
debug = false

[mysql]
#host = "127.0.0.1"
host = "192.168.10.224"
port = 3306
user = "xiaolin"
password = "ADMIN@forlty1314"
dbName = ""
charset = "utf8mb4"
pool = 100

[redis]
#host = "127.0.0.1"
host = "192.168.10.224"
port = 6706
password = "ADMIN@forlty1314"
dbName = 0
pool = 20

[mongo]
host = ""
user = ""
port = 27017
password = ""
pool = 20

[file]
path = "static/file/"